docs/AboutUs.md

Deanson ~ About Us

---

src/main/java/seedu/duke/AddCommand.java
src/main/java/seedu/duke/Command.java
src/main/java/seedu/duke/Commands.java
src/main/java/seedu/duke/DeleteCommand.java
src/main/java/seedu/duke/ExitCommand.java
src/main/java/seedu/duke/LeBook.java
src/main/java/seedu/duke/LeBookException.java
src/main/java/seedu/duke/ListCommand.java
src/main/java/seedu/duke/UpdateStatusCommand.java

Command classes creation for parser and LeBook Exception implemented

---

src/main/java/seedu/duke/Book.java
src/main/java/seedu/duke/Ui.java

added book and ui classes
issues fixed:
fixes #22 
fixes #25

UI and Book class added

---

src/main/java/seedu/duke/BookManager.java

Created BookManager skeleton code

---

build.gradle
src/main/java/seedu/duke/LeBook.java
src/main/java/seedu/duke/parser/Parser.java

Add parser to parse user input and call relevant command

---

src/main/java/seedu/duke/LeBook.java
src/main/java/seedu/duke/Storage.java

Implement storage

---

build.gradle
src/main/java/seedu/duke/Book.java
src/main/java/seedu/duke/LeBook.java

updated assertions

---

src/main/java/seedu/duke/book/Book.java
src/main/java/seedu/duke/ui/Ui.java

Addition of setStatus in Book class and scanner function in Ui class

---

src/main/java/seedu/duke/LeBook.java
src/main/java/seedu/duke/storage/Storage.java

Fix Storage branch

---

src/main/java/seedu/duke/LeBook.java
src/main/java/seedu/duke/book/Book.java
src/main/java/seedu/duke/commands/AddCommand.java
src/main/java/seedu/duke/commands/DeleteCommand.java
src/main/java/seedu/duke/commands/UpdateStatusCommand.java
src/main/java/seedu/duke/storage/Storage.java

Fixed overall code structure

---

src/main/java/seedu/duke/book/Book.java
src/main/java/seedu/duke/parser/Parser.java
src/main/java/seedu/duke/storage/Storage.java

Fixed minor bugs

---

src/main/java/seedu/duke/commands/AddCommand.java
src/main/java/seedu/duke/commands/DeleteCommand.java
src/main/java/seedu/duke/commands/UpdateStatusCommand.java
src/main/java/seedu/duke/storage/Storage.java

Updated command classes

---

src/main/java/seedu/duke/book/BookManager.java

updated deleteBook

---

src/main/java/seedu/duke/book/Book.java
src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/storage/Storage.java

Fix bug in loading file

---

src/main/java/seedu/duke/book/Book.java
src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/commands/AddCommand.java
src/main/java/seedu/duke/commands/Command.java
src/main/java/seedu/duke/commands/DeleteCommand.java
src/main/java/seedu/duke/commands/ExitCommand.java
src/main/java/seedu/duke/commands/ListCommand.java
src/main/java/seedu/duke/commands/UpdateStatusCommand.java

Formatting Files

---

src/main/java/seedu/duke/book/BookManager.java

added javadoc comments 

---

src/main/java/seedu/duke/commands/AddCommand.java
src/main/java/seedu/duke/commands/DeleteCommand.java
src/main/java/seedu/duke/commands/ExitCommand.java
src/main/java/seedu/duke/commands/ListCommand.java
src/main/java/seedu/duke/commands/UpdateStatusCommand.java

Add Assertions to Command Classes

---

src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/commands/AddCommand.java
src/main/java/seedu/duke/commands/DeleteCommand.java
src/main/java/seedu/duke/commands/ExitCommand.java
src/main/java/seedu/duke/commands/ListCommand.java
src/main/java/seedu/duke/commands/UpdateStatusCommand.java

Deanson v1.0#fix8

---

src/main/java/seedu/duke/parser/Parser.java
src/test/java/seedu/duke/parser/ParserTest.java

Include assertions and j unit tests for parser

Update parser to include assertions and JUnit test

---

src/main/java/seedu/duke/storage/Storage.java
src/test/java/seedu/duke/storage/StorageTest.java

Branch j unit#2#

---

src/test/java/seedu/duke/book/BookManagerTest.java

Added test cases for updateBookStatus() method

---

src/main/java/seedu/duke/ui/Ui.java

edited ui class to include print with separator

---

src/main/java/seedu/duke/book/Book.java
src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/commands/ListOverdueCommand.java
src/main/java/seedu/duke/parser/Parser.java
src/main/java/seedu/duke/storage/Storage.java

fixes #107
fixes #104 
fixes #105

added functionality for borrowed books return due dates

---

src/main/java/seedu/duke/storage/Storage.java

Refactor code
Removoe Redundancy

Addressed comments

---

docs/DeveloperGuide.md

Added bookmanager skeleton explanation in DG

---

docs/DeveloperGuide.md

added DG for Ui class and return due date related features

added DG for Ui class and return due date related features

---

docs/DeveloperGuide.md

Branch wayne(v2.0)#1

---

docs/DeveloperGuide.md

Include parser in developer guide

---

src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/commands/DeleteCommand.java
src/main/java/seedu/duke/commands/UpdateStatusCommand.java
src/main/java/seedu/duke/parser/Parser.java
src/test/java/seedu/duke/book/BookManagerTest.java
src/test/java/seedu/duke/parser/ParserTest.java

Update parser to pass in book index

---

src/main/java/seedu/duke/LeBook.java
src/main/java/seedu/duke/Shelving/Shelves/Shelf.java
src/main/java/seedu/duke/Shelving/Shelves/Shelves.java
src/main/java/seedu/duke/Shelving/ShelvesManager.java
src/main/java/seedu/duke/book/Book.java
src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/book/ShelfBookManager.java
src/main/java/seedu/duke/commands/AddCommand.java
src/main/java/seedu/duke/commands/Command.java
src/main/java/seedu/duke/commands/DeleteCommand.java
src/main/java/seedu/duke/commands/ExitCommand.java
src/main/java/seedu/duke/commands/ListCommand.java
src/main/java/seedu/duke/commands/ListOverdueCommand.java
src/main/java/seedu/duke/commands/UpdateStatusCommand.java
src/main/java/seedu/duke/library/Library.java

able to deleteBooks from shelves

---

src/main/java/seedu/duke/Shelving/Shelves/Shelf.java
src/main/java/seedu/duke/Shelving/Shelves/Shelves.java
src/main/java/seedu/duke/Shelving/ShelvesManager.java
src/main/java/seedu/duke/book/Book.java
src/main/java/seedu/duke/book/ShelfBookManager.java
src/main/java/seedu/duke/library/Library.java
src/test/java/seedu/duke/shelf/ShelfTest.java

Implemented the addBook function to the shelves

---

src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/commands/ListBorrowedCommand.java
src/main/java/seedu/duke/library/Library.java
src/main/java/seedu/duke/parser/Parser.java

Add code to implement listing of borrowed books

---

src/main/java/seedu/duke/Shelving/Shelves/Shelf.java
src/test/java/seedu/duke/shelf/ShelfTest.java

Wrote tests,

---

src/main/java/seedu/duke/Shelving/Shelves/Shelf.java
src/main/java/seedu/duke/Shelving/Shelves/Shelves.java
src/main/java/seedu/duke/Shelving/ShelvesManager.java
src/main/java/seedu/duke/commands/AddCommand.java
src/main/java/seedu/duke/commands/Commands.java
src/main/java/seedu/duke/commands/HelpCommand.java
src/main/java/seedu/duke/commands/ListCommand.java
src/main/java/seedu/duke/parser/Parser.java
src/main/java/seedu/duke/ui/Ui.java
src/test/java/seedu/duke/shelf/ShelfTest.java
src/test/java/seedu/duke/ui/UiTest.java

resolves #141 
resolves #103 
resolves #99 
todo: listShelf()

Implementation of the "help" command, Wrote testing for add to shelf

---

src/main/java/seedu/duke/library/Library.java
src/main/java/seedu/duke/shelving/ShelvesManager.java
src/main/java/seedu/duke/shelving/shelves/Shelf.java
src/main/java/seedu/duke/shelving/shelves/Shelves.java

......for classes: Library, ShelvesManager, Shelf, Shelves.

Wrote some javadoc for deletion of a book

---

src/main/java/seedu/duke/shelving/shelves/Shelf.java
src/test/java/seedu/duke/shelf/ListShelfCommandTest.java

implemented test for list shelf

Fix listing shelf when deleted a book

---

src/main/java/seedu/duke/exception/NoSuchSectionException.java
src/main/java/seedu/duke/shelving/ShelvesManager.java
src/main/java/seedu/duke/shelving/shelves/Shelf.java
src/main/java/seedu/duke/shelving/shelves/Shelves.java

Fix bug on listing the shelf that is not in the section

---

src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/commands/StatisticsCommand.java
src/main/java/seedu/duke/library/Library.java
src/main/java/seedu/duke/parser/Parser.java
src/main/java/seedu/duke/ui/Ui.java
src/test/java/seedu/duke/book/BookManagerTest.java
src/test/java/seedu/duke/ui/UiTest.java

fixes #178 
minor bug fixes and test cases added too

Stats feature

---

src/main/java/seedu/duke/library/Library.java
src/main/java/seedu/duke/parser/Parser.java

Fixes #108 
- Implement updateBookStatus in Library class
- Ensure all genre inputs are changed to lowercase for consistency

Jermaine minor fix

---

src/main/java/seedu/duke/LeBook.java
src/main/java/seedu/duke/library/Library.java
src/main/java/seedu/duke/shelving/ShelvesManager.java
src/main/java/seedu/duke/shelving/shelves/Shelf.java
src/main/java/seedu/duke/shelving/shelves/Shelves.java
src/main/java/seedu/duke/storage/Storage.java
src/main/java/seedu/duke/ui/Ui.java
src/test/java/seedu/duke/shelf/LibraryTest.java
src/test/java/seedu/duke/shelf/ShelvesManagerTest.java
src/test/java/seedu/duke/shelf/shelftest/AddTests.java
src/test/java/seedu/duke/storage/StorageTest.java

TODO: fix minor bugs, make code more defensive

Fix the loading of files

---

src/main/java/seedu/duke/book/Book.java
src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/storage/Storage.java
src/test/java/seedu/duke/book/BookManagerTest.java
src/test/java/seedu/duke/book/BookTest.java
src/test/java/seedu/duke/shelf/LibraryTest.java
src/test/java/seedu/duke/shelf/ShelvesManagerTest.java
src/test/java/seedu/duke/shelf/ShelvesTest.java
src/test/java/seedu/duke/shelf/shelftest/DeleteTests.java

Quantity feature

---

src/main/java/seedu/duke/LeBook.java
src/main/java/seedu/duke/book/Book.java
src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/member/MemberManager.java
src/main/java/seedu/duke/storage/Storage.java
src/test/java/seedu/duke/book/BookManagerTest.java
src/test/java/seedu/duke/book/BookTest.java
src/test/java/seedu/duke/member/MemberManagerTest.java
src/test/java/seedu/duke/shelf/ShelvesManagerTest.java
src/test/java/seedu/duke/shelf/ShelvesTest.java
src/test/java/seedu/duke/shelf/shelftest/DeleteTests.java
src/test/java/seedu/duke/storage/StorageTest.java

Implement saving of members in storage

---

src/main/java/seedu/duke/storage/Storage.java

Fix minor bugs in storage regarding loading and saving book

---

src/main/java/seedu/duke/LeBook.java
src/main/java/seedu/duke/book/Book.java
src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/book/QuantityManager.java
src/main/java/seedu/duke/commands/ListBookQuantityCommand.java
src/main/java/seedu/duke/commands/StatisticsCommand.java
src/main/java/seedu/duke/library/Library.java
src/main/java/seedu/duke/parser/Parser.java
src/main/java/seedu/duke/shelving/ShelvesManager.java
src/main/java/seedu/duke/shelving/shelves/Shelf.java
src/main/java/seedu/duke/shelving/shelves/Shelves.java
src/main/java/seedu/duke/storage/Storage.java
src/test/java/seedu/duke/book/BookManagerTest.java
src/test/java/seedu/duke/book/BookTest.java
src/test/java/seedu/duke/book/QuantityManagerTest.java
src/test/java/seedu/duke/shelf/LibraryTest.java
src/test/java/seedu/duke/shelf/ShelvesManagerTest.java
src/test/java/seedu/duke/shelf/ShelvesTest.java
src/test/java/seedu/duke/shelf/shelftest/DeleteTests.java

satisfies #176 
Removed the quantity attribute in the Book class
created a list Quantity (of specific title and author)

Fix issues related to borrowing

---

src/main/java/seedu/duke/parser/Parser.java
src/test/java/seedu/duke/parser/ParserTest.java

- Handle exceptions properly
- Add author tag

Implement minor changes to parser

---

src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/member/MemberManager.java

Fix bug regarding the listing of users with overdue books after the book is deleted

Fix bug regarding listing after deleting books

---

src/main/java/seedu/duke/LeBook.java
src/main/java/seedu/duke/book/UndoManager.java
src/main/java/seedu/duke/commands/AddCommand.java
src/main/java/seedu/duke/commands/Command.java
src/main/java/seedu/duke/commands/DeleteByBookCommand.java
src/main/java/seedu/duke/commands/DeleteByIndexCommand.java
src/main/java/seedu/duke/commands/UndoCommand.java
src/main/java/seedu/duke/commands/UpdateStatusCommand.java
src/main/java/seedu/duke/library/Library.java
src/main/java/seedu/duke/parser/Parser.java
src/main/java/seedu/duke/shelving/ShelvesManager.java
src/main/java/seedu/duke/ui/Ui.java
src/test/java/seedu/duke/book/BookManagerTest.java
src/test/java/seedu/duke/commands/AddCommandTest.java
src/test/java/seedu/duke/commands/DeleteByBookCommandTest.java
src/test/java/seedu/duke/commands/DeleteByIndexCommandTest.java
src/test/java/seedu/duke/commands/UpdateStatusCommandTest.java
src/test/java/seedu/duke/shelf/LibraryTest.java
src/test/java/seedu/duke/storage/StorageTest.java
src/test/java/seedu/duke/ui/UiTest.java

commented out some junit tests
fixes #179

added feature undo

---

src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/commands/SearchByIDCommand.java
src/main/java/seedu/duke/parser/Parser.java
src/main/java/seedu/duke/ui/Ui.java

Fix error for qty
Updated name to ID instead of shelf

Edited searchbyid and fixed bug for UI

---

src/main/java/seedu/duke/parser/Parser.java
src/test/java/seedu/duke/parser/ParserTest.java

- Add more JUnit parser tests
- Uncomment statistics command
- Update exception/error messages in parser

Add more parser tests and implement minor change in parser

---

src/main/java/seedu/duke/book/UndoManager.java
src/main/java/seedu/duke/commands/Command.java
src/main/java/seedu/duke/commands/ExitCommand.java
src/main/java/seedu/duke/commands/HelpCommand.java
src/main/java/seedu/duke/commands/ListBookQuantityCommand.java
src/main/java/seedu/duke/commands/ListBorrowedCommand.java
src/main/java/seedu/duke/commands/ListCommand.java
src/main/java/seedu/duke/commands/ListOverdueCommand.java
src/main/java/seedu/duke/commands/ListOverdueUsersCommand.java
src/main/java/seedu/duke/commands/ListShelfCommand.java
src/main/java/seedu/duke/commands/SearchByAuthorCommand.java
src/main/java/seedu/duke/commands/SearchByGenreCommand.java
src/main/java/seedu/duke/commands/SearchByIDCommand.java
src/main/java/seedu/duke/commands/SearchByTitleCommand.java
src/main/java/seedu/duke/commands/StatisticsCommand.java
src/main/java/seedu/duke/commands/UndoCommand.java

minor bug fix for undo function

---

src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/commands/AddCommand.java
src/main/java/seedu/duke/shelving/shelves/Shelf.java
src/main/java/seedu/duke/storage/Storage.java
src/main/java/seedu/duke/ui/Ui.java
src/test/java/seedu/duke/commands/AddCommandTest.java
src/test/java/seedu/duke/commands/DeleteByBookCommandTest.java
src/test/java/seedu/duke/commands/DeleteByIndexCommandTest.java
src/test/java/seedu/duke/commands/ListOverdueCommandTest.java
src/test/java/seedu/duke/commands/StatisticsCommandTest.java
src/test/java/seedu/duke/commands/UpdateStatusCommandTest.java
src/test/java/seedu/duke/shelf/shelftest/AddTests.java
src/test/java/seedu/duke/storage/StorageTest.java

improve the help command. Also improved formatting when adding a book.

Fix test bugs.

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/duke/book/QuantityManager.java
src/main/java/seedu/duke/commands/ListBookQuantityCommand.java
src/main/java/seedu/duke/member/MemberManager.java
src/test/java/seedu/duke/book/BookManagerTest.java
src/test/java/seedu/duke/book/QuantityManagerTest.java
src/test/java/seedu/duke/member/MemberManagerTest.java

- Fix bug where book quantity command is called with empty title and/or empty author
- Include JUnit tests for QuantityManager

Jermaine fix quantity

---

src/main/java/seedu/duke/commands/DeleteByBookCommand.java
src/main/java/seedu/duke/commands/DeleteByIDCommand.java
src/main/java/seedu/duke/library/Library.java
src/test/java/seedu/duke/commands/DeleteByIDCommandTest.java

Junit test for delete by id command

undo feature added to deletebyid

---

src/main/java/seedu/duke/commands/DeleteByBookCommand.java
src/main/java/seedu/duke/commands/DeleteByIDCommand.java
src/main/java/seedu/duke/commands/DeleteByIndexCommand.java
src/main/java/seedu/duke/library/Library.java
src/main/java/seedu/duke/parser/Parser.java
src/main/java/seedu/duke/shelving/ShelvesManager.java
src/main/java/seedu/duke/shelving/shelves/ActionShelves.java
src/main/java/seedu/duke/shelving/shelves/AdventureShelves.java
src/main/java/seedu/duke/shelving/shelves/HorrorShelves.java
src/main/java/seedu/duke/shelving/shelves/MysteryShelves.java
src/main/java/seedu/duke/shelving/shelves/NonFictionShelves.java
src/main/java/seedu/duke/shelving/shelves/RomanceShelves.java
src/main/java/seedu/duke/shelving/shelves/SciFiShelves.java
src/main/java/seedu/duke/shelving/shelves/Shelf.java
src/main/java/seedu/duke/shelving/shelves/Shelves.java
src/test/java/seedu/duke/parser/ParserTest.java
src/test/java/seedu/duke/shelf/ShelvesTest.java
src/test/java/seedu/duke/shelf/shelftest/DeleteTests.java

author tagged certain methods and wrote javadocs for deleteBook methods

author tagging and javadocs

---

src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/commands/UpdateStatusCommand.java
src/main/java/seedu/duke/parser/Parser.java
src/test/java/seedu/duke/commands/UpdateStatusCommandTest.java

Jermaine fix book manager bug

---

src/main/java/seedu/duke/LeBook.java
src/main/java/seedu/duke/shelving/shelves/Shelf.java
src/main/java/seedu/duke/storage/Storage.java

Clean storage when txt file is tampered with.
fixes #292 #277

fixing bug on book ID.

---

docs/UserGuide.md

ug fix for adding information about book id

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/parser/Parser.java

Delete error fix

---

src/main/java/seedu/duke/ui/Ui.java

Changed naming convention from "SHELF"  to "ID"

Updated shelf -> id naming in UI

---

src/main/java/seedu/duke/book/Book.java
src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/member/MemberManager.java
src/main/java/seedu/duke/parser/Parser.java
src/main/java/seedu/duke/ui/Ui.java
src/test/java/seedu/duke/member/MemberManagerTest.java
src/test/java/seedu/duke/parser/ParserTest.java

Fixes #288 and modifies the various list command outputs to be consistent

Update list output formatting and modify list users command

---

src/main/java/seedu/duke/parser/Parser.java

Fix bug regarding parsing of list shelf input

---

docs/team/eth4n22.md

updated Ethan PPP

---

src/main/java/seedu/duke/book/BookManager.java
src/main/java/seedu/duke/commands/ListBookQuantityCommand.java
src/main/java/seedu/duke/ui/Ui.java

Jermaine minor fix v3
